---
title: "Ensino"
output:
  html_document:
    toc_float: false
    fig_width: 1
    include:
      after_body: footer.html      
---

----

### **Pós-Graduação**

#### 2S2017

- MI416 - Introdução aos Modelos Lineares 
</br>

----

### **Graduação**

#### 1S2020

- [ME951 A - Estatística e Probabilidade I](me951_1s2020.html)
</br>

- ME712 A -  Consultoria Estatística I
</br>

- ME812 A -  Consultoria Estatística II
</br>

#### 2S2019

- [ME414 H - Estatística para Experimentalistas](me414_2s2019.html)
</br>

- [ME720 A -  Modelos Lineares Generalizados](me720_2s2019.html)
</br>

#### 1S2019

- [ME951 A - Estatística e Probabilidade I](me951_1s2019.html)
</br>


#### 2S2018

- [ME414 A - Estatística para Experimentalistas](me414_2s2018.html)
</br>

- [ME710 A - Assessoria Estatística](Disciplinas/EmentaME710_2S2018.pdf)
</br>

- [ME712 A -  Consultoria Estatística I](Disciplinas/EmentaME712e812_2S2018.pdf)
</br>

- [ME810 A - Estágio Supervisionado](Disciplinas/EmentaME810_2S2018.pdf)
</br>

- [ME812 A -  Consultoria Estatística II](Disciplinas/EmentaME712e812_2S2018.pdf)
</br>

- [ME850 A - Seminários de Estatística](Disciplinas/EmentaME850_2S2018.pdf)
</br>

#### 1S2018

- [ME111 A e B - Laboratório de Estatística](me111_1s2018.html)
</br>

- [ME639 A -  Metodologias e Técnicas de Pesquisa](me639_1s2018.html)
</br>

- [ME710 A - Assessoria Estatística](Disciplinas/EmentaME710_1s2018.pdf)
</br>

- [ME712 A -  Consultoria Estatística I](Disciplinas/EmentaME712_1s2018.pdf)
</br>

- [ME810 A - Estágio Supervisionado](Disciplinas/EmentaME810_1s2018.pdf)
</br>

- [ME850 A - Seminários de Estatística](Disciplinas/EmentaME850_1s2018.pdf)
</br>

#### 2S2017

- ME414 H - Estatística para Experimentalistas
</br>

----

