---
title: "ME414 - Estatística para Experimentalistas"
output:
  html_document:
    fig_width: 1
    toc_float: false
    include:
      after_body: footer.html  
---

----

**Segundo Semestre de 2018**

**Aulas:** Segundas (CB15) e Quintas (PB16), 21h00-23h00 

**AVISO:**<span style="color:red"> REVISÃO DO EXAME - DIA 13/12 as 16h.  </span>

----

### **Informações Gerais**

**Instruções para a prova:**

- O(a) aluno(a) deverá apresentar seu RA e RG/CNH quando entregar a prova e assinar presença.

- O(a) aluno(a) só poderá sair da sala após 40 minutos do início da prova, mesmo que já tenha finalizado a prova. Após a saída do(a) primeiro(a) aluno(a) não será permitida a entrada de nenhum(a) outro(a) aluno(a).

- O(a) aluno(a) poderá utilizar apenas caneta, lápis, borracha e calculadora. Não poderá utilizar a calculadora do celular.

- Não será permitido empréstimo de material de qualquer tipo entre alunos durante a prova. 

- Para a P2 o(a) aluno(a) deverá levar as [tabelas](Disciplinas/ME_414_2s2018/Tabelas.pdf). **As tabelas não poderão estar rasuradas.** 

- [Formulário](Disciplinas/ME_414_2s2018/Formulario.pdf): Uma cópia será fornecida durante a prova.


----

### **Ementa**

- [Ementa](Disciplinas/ME_414_2s2018/Ementa.pdf)


**Programa**

  1. Estatística Descritiva
    (a) Introdução;
    (b) Classificação de variáveis;	
    (c) Variáveis Categóricas: Distribuição de Frequência (tabelas e gráficos de barras);	
    (d) Variáveis Contínuas: Histograma, Ramo e Folha, Box-Plot, Esquema dos cinco números, Medidas de tendência central e de dispersão;
    (e) Análise descritivas bivariada: Diagrama de dispersão, Correlação, Tabelas de contingência e gráficos de barras.

  2. Probabilidade
    (a) Definição; Espaço amostral; Eventos; Operações com eventos; Partições do espaço amostral;
    (b) Probabilidade Condicional; Independência de Eventos;
    (c) Teorema de Bayes;
    (d) Variáveis aleatórias discretas; Distribuições de Probabilidade Discreta; Função de Distribuição Acumulada (FDA); Valor esperado e variância; Distribuições discretas: Uniforme, Bernoulli, Binomial, Geométrica, Hipergeométrica e Poisson; Aproximação da Binomial pela Poisson;
    (e) Variáveis aleatórias continuas: Função de densidade, Função de Distribuição Acumulada (FDA), Valor esperado e variância, Distribuições continuas: Uniforme, Exponencial, Normal; Aproximação da Binomial pela Normal.

  3. Amostragem e Inferência Estatística
    (a) População e Amostra; Amostra Aleatória Simples; Estatística e Parâmetro; Distribuições Amostrais; Teorema Central do Limite;
    (b) Estimação, Pontual e por Intervalo;
    (c) Testes de Hipóteses: para médias e proporções (uma e duas populações);
    (d) Testes de Aderência, Independência e Homogeneidade.

  4. Regressão Linear Simples

**Atendimento**

- Atendimento (Professor): Segundas, das 18h às 19h - Sala 234.
- Atendimento PED (Francisco Hildemar): Terças, das 18h às 19h - Sala 225.

**Referências Bibliográficas**

- Bussab, W. O. \& Morettin, P. A. (1987). *Estatística Básica*. Atual Editora Ltda., São Paulo.
- Magalhães, M. N., \& de Lima, A. C. P. (2001). *Noções de probabilidade e estatística*. São Paulo: IME-USP.
- Ross, S. M. (2010). *Introductory Statistics.*
- Diez, D. M.; Barr, C. D.; Çetinkaya-Rundel, M. (2015). *OpenIntro Statistics.*


**Critérios de Avaliação**

- A média final (MF) será a média ponderada de duas provas (P1 e P2). Os alunos que obtiverem nota superior ou igual a **$\small 6,0$** estarão **aprovados**. 

- Então, o aluno será aprovado se
  $$\small \mbox{MF} = 0,4*\mbox{P1} + 0,6*\mbox{P2} \geq 6,0.$$

- Os alunos que obtiverem nota final inferior a $\small 6,0$ deverão realizar um exame final. A nota final do curso será a média aritmética simples da nota final do semestre e a nota do exame final, ou seja, 
$$\small \mbox{NF} = \frac{\mbox{MF} + \mbox{Exame}}{2}.$$

  Observações: 

  1. Frequência mínima para aprovação é de $\small 75\%$.
  2. Para a realização do Exame Final, será utilizado o Artigo 57 do Regimento Geral de Graduação. Aqueles que    obtiverem $\small \mbox{MF} \geq 6,0$ estão dispensados do Exame e Aprovados na disciplina. Aqueles que obtiverem $\small 2,5 \leq \mbox{MF} \leq 6,0$ e frequência mínima de $\small 75\%$ poderão fazer o Exame Final. Aqueles com $\small \mbox{MF} < 2,5$ ou frequência menor que $\small 75\%$ não poderão fazer o Exame e estão Reprovados.
  3. O aluno deverá apresentar o RG e o RA durante as provas, se o aluno não apresentar os dois documentos sua    prova será anulada.
  4. Caso o aluno não compareça no dia da P1 ou da P2, deverá enviar a justificativa pelo email. Os alunos com justificativas aceitas poderão realizar a prova substitutiva, que poderá contemplar qualquer conteúdo ministrado durante o semestre.

----

### **Datas Importantes**

- Prova 1 (P1): 	20/09/18	 

- Prova 2 (P2):   22/11/18	 

- Prova Substitutiva:	29/11/18 

- Exame final:        10/12/18 

---- 

### **Aulas**

- [Parte 1](Disciplinas/ME_414_2s2018/parte01/parte01.html)
- [Parte 2](Disciplinas/ME_414_2s2018/parte02/parte02.html)
- [Parte 3](Disciplinas/ME_414_2s2018/parte03/parte03.html)
- [Parte 4](Disciplinas/ME_414_2s2018/parte04/parte04.html)
- [Parte 5](Disciplinas/ME_414_2s2018/parte05/parte05.html)
- [Parte 6](Disciplinas/ME_414_2s2018/parte06/parte06.html)
- [Parte 7](Disciplinas/ME_414_2s2018/parte07/parte07.html)
- [Parte 8](Disciplinas/ME_414_2s2018/parte08/parte08.html) ( [Código R](Disciplinas/ME_414_2s2018/parte08/PortaDosDesesperados.R) )
- [Parte 9](Disciplinas/ME_414_2s2018/parte09/parte09.html)
- [Parte 10](Disciplinas/ME_414_2s2018/parte10/parte10.html)
- [Parte 11](Disciplinas/ME_414_2s2018/parte11/parte11.html)
- [Parte 12](Disciplinas/ME_414_2s2018/parte12/parte12.html)
- [Parte 13](Disciplinas/ME_414_2s2018/parte13/parte13.html)
- [Parte 14](Disciplinas/ME_414_2s2018/parte14/parte14.html)
- [Parte 15](Disciplinas/ME_414_2s2018/parte15/parte15.html)
- [Parte 16](Disciplinas/ME_414_2s2018/parte16/parte16.html)
- [Parte 17](Disciplinas/ME_414_2s2018/parte17/parte17.html)
- [Parte 18](Disciplinas/ME_414_2s2018/parte18/parte18.html)
- [Parte 19](Disciplinas/ME_414_2s2018/parte19/parte19.html)
- [Parte 20](Disciplinas/ME_414_2s2018/parte20/parte20.html)
- [Parte 21](Disciplinas/ME_414_2s2018/parte21/parte21.html)
- [Parte 22](Disciplinas/ME_414_2s2018/parte22/parte22.html)
- [Parte 23](Disciplinas/ME_414_2s2018/parte23/parte23.html)
- [Parte 24](Disciplinas/ME_414_2s2018/parte24/parte24.html)


---- 

### **Listas**

- [Lista 1](Disciplinas/ME_414_2s2018/Lista1.pdf): Estatística Descritiva

- [Lista 2](Disciplinas/ME_414_2s2018/Lista2.pdf): Probabilidade e Variáveis Aleatórias Discretas
      
      <!-- - [Gabarito](Disciplinas/ME_414_2s2018/Lista2Gabarito.pdf) -->

- [Lista 3](Disciplinas/ME_414_2s2018/Lista3.pdf): Variáveis Aleatóorias Contínuas

- [Lista 4](Disciplinas/ME_414_2s2018/Lista4.pdf): Inferência Estatística

- [Lista Extra](Disciplinas/ME_414_2s2018/ListaExtra_Veronica.pdf) (Verônica)

</br>

- [Tabelas das distribuições](Disciplinas/ME_414_2s2018/Tabelas.pdf): Tabelas para serem usadas na resolução dos exercícios. 
    
----

### **Notas**

      
- [Notas](Disciplinas/ME_414_2s2018/notas.html)
      
----
