---
title: "Publicações"
output:
  html_document:
    fig_width: 1
---

### Artigos Científicos

----

- LACHOS, VICTOR H.; **MATOS, LARISSA A.**; CASTRO, LUIS M.; CHEN, MING-HUI (2018). *Flexible Longitudinal Linear Mixed Models for Multiple Censored Responses Data.* (Statistics in Medicine) \medskip
</br>

- **MATOS, LARISSA A.**; CASTRO, LUIS M. ; CABRAL, CELSO R. B. ; LACHOS, VICTOR H. *Multivariate measurement error models based on Student- distribution under censored responses.* STATISTICS, v. 52, p. 1395-1416, 2018. [Link.](https://www.tandfonline.com/doi/abs/10.1080/02331888.2018.1527841) \medskip
</br>

- **MATOS, LARISSA A.**; LACHOS, VÍCTOR H.; LIN, TSUNG-I; CASTRO, LUIS M. *Heavy-tailed longitudinal regression models for censored data: a robust parametric approach*. TEST, v. -, p. -, 2018. [Link.](https://link.springer.com/article/10.1007/s11749-018-0603-5) \medskip
</br>

- LACHOS, VICTOR H.; **MATOS, LARISSA A.**; BARBOSA, THAIS S.; GARAY, Aldo M.; DEY, DIPAK K. *Influence diagnostics in spatial models with censored response.* ENVIRONMETRICS, v. 28, p. e2464, 2017. [Link.](https://onlinelibrary.wiley.com/doi/abs/10.1002/env.2464)\medskip
</br>

- **MATOS, LARISSA A.**; CASTRO, LUIS M.; LACHOS, VICTOR H. *Censored mixed-effects models for irregularly observed repeated measures with applications to HIV viral loads.* TEST, v. 25, p. 627-653, 2016. [Link.](https://link.springer.com/article/10.1007/s11749-016-0486-2)\medskip
</br>

- **MATOS, LARISSA A.**; BANDYOPADHYAY, DIPANKAR; CASTRO, LUIS M.; LACHOS, VICTOR H. *Influence assessment in censored mixed-effects models using the multivariate Students-t.* JOURNAL OF MULTIVARIATE ANALYSIS, v. 141, p. 104-117, 2015. [Link.](https://www.sciencedirect.com/science/article/pii/S0047259X15001591)\medskip
</br>

- MASSUIA, MONIQUE B.; CABRAL, CELSO RÔMULO BARBOSA; **MATOS, LARISSA A.**; LACHOS, VICTOR H. *Influence diagnostics for Student- t censored linear regression models.* Statistics (Berlin), v. 49, p. 1-21, 2014. [Link.](https://www.tandfonline.com/doi/abs/10.1080/02331888.2014.958489) \medskip
</br>

- **MATOS, LARISSA A.**; PRATES, MARCOS O.; CHEN, MING-HUI; LACHOS, VICTOR H. *Likelihood Based Inference Mixed-Effects Models with Censored Responses Using the Multivariate-t Distribution.* Statistica Sinica, v. 23, p. 1323-1345, 2013. [Link.](https://www.jstor.org/stable/24310797?casa_token=M6ta3whn1KwAAAAA:ufWMXvGQRiHve3_lOgpXTDp8hJTCk-I4_YNUet8rY0iSpveLNEsLkarqhji6npYGYRYYnL919UoaQ9qS356eu0cCTQ2l1RaEMgU_Vk-RDql_CfEPYWkd#metadata_info_tab_contents) \medskip
</br>

- **MATOS, LARISSA A.**; LACHOS, VICTOR H.; BALAKRISHNAN, N.; LABRA, FILIDOR V. *Influence diagnostics in linear and nonlinear mixed-effects models with censored data.* Computational Statistics & Data Analysis (Print), v. 57, p. 450-464, 2013. [Link.](https://www.sciencedirect.com/science/article/pii/S0167947312002629) \medskip
</br>


