---
output:
  html_document:
    fig_width: 1
---

<style>
.column-left{
  float: left;
  width: 48%;
  text-align: left;
}
.column-right{
  float: right;
  width: 48%;
  text-align: left;
}
.column-center{
  float: right;
  width: 4%;
  text-align: left;
}
.column{
  float: left;
  width: 100%;
  text-align: left;
}  
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(reshape2)
library(ggplot2)
# library(printr)
library(knitr)
```

## Notas

----

|     RA|   P1|   P2|SUB  |   MF|EXAME |   NF| Faltas|S         |
|:-----:|:---:|:---:|:---:|:---:|:----:|:---:|------:|---------:|
|  96854| 5,55| 2,25|1,75 | 3,57|4,25  | 3,9|      1|<span style="color:red"> REPROVADO </span>          |
| 121337| 0,00| 0,00|-    | 0,00|-     | 0,0|     28|<span style="color:maroon"> REPROVADO FALTA/NOTA </span>  |
| 140689| 9,30| 4,75|-    | 6,57|-     | 6,6|      4|<span style="color:green"> APROVADO </span>             |
| 148613| 4,95| 0,00|-    | 1,98|-     | 1,0|     12|<span style="color:maroon"> REPROVADO FALTA/NOTA </span>  |
| 154511| 7,30| 9,00|-    | 8,32|-     | 8,3|      6|<span style="color:green"> APROVADO </span>             |
| 155006| 9,25| 7,75|-    | 8,35|-     | 8,4|      8|<span style="color:green"> APROVADO </span>             |
| 156994| 9,50| 7,75|-    | 8,45|-     | 8,5|      4|<span style="color:green"> APROVADO </span>             |
| 156997| 9,40| 9,75|-    | 9,61|-     | 9,6|      0|<span style="color:green"> APROVADO </span>             |
| 158062| 8,05| 5,50|-    | 6,52|-     | 6,5|      6|<span style="color:green"> APROVADO </span>             |
| 159639| 6,50| 2,00|-    | 3,80|6,25  | 5,0|      8|<span style="color:green"> APROVADO </span>             |
| 166785| 4,30| 0,00|-    | 1,72|-     | 0,9|      9|<span style="color:maroon"> REPROVADO FALTA/NOTA </span>  |
| 168158| 8,00| 6,00|-    | 6,80|-     | 6,8|      8|<span style="color:green"> APROVADO </span>             |
| 171081| 2,80| 1,50|-    | 2,02|-     | 1,0|      5|<span style="color:red"> REPROVADO </span>          |
| 171431| 3,55| 0,00|-    | 1,42|      | 0,7|     18|<span style="color:maroon"> REPROVADO FALTA/NOTA </span>  |
| 171456| 2,80| 1,00|2,75 | 2,77|1,50  | 2,1|      8|<span style="color:red"> REPROVADO </span>          |
| 171489| 7,85| 3,75|6,50 | 7,04|-     | 7,0|      8|<span style="color:green"> APROVADO </span>             |
| 172657| 3,25| 0,00|-    | 1,30|-     | 0,7|      9|<span style="color:maroon"> REPROVADO FALTA/NOTA </span>  |
| 174439| 5,30| 1,50|4,75 | 4,97|7,25  | 6,1|      8|<span style="color:green"> APROVADO </span>             |
| 175049| 6,65| 2,50|4,25 | 5,21|-     | 2,6|     11|<span style="color:maroon"> REPROVADO FALTA/NOTA </span>  |
| 175358| 0,00| 4,75|7,00 | 5,65|-     | 2,9|     27|<span style="color:maroon"> REPROVADO FALTA/NOTA </span>  |
| 175677| 3,05| 2,25|3,00 | 3,02|-     | 1,5|      5|<span style="color:red"> REPROVADO </span>          |
| 176225| 3,75| 4,00|4,50 | 4,20|7,00  | 5,6|      6|<span style="color:green"> APROVADO </span>             |
| 176234| 9,25| 1,25|4,25 | 6,25|-     | 6,3|      8|<span style="color:green"> APROVADO </span>             |
| 177584| 7,85| 3,75|5,00 | 6,14|-     | 6,1|      7|<span style="color:green"> APROVADO </span>             |
| 183517| 8,75| 5,75|-    | 6,95|-     | 7,0|      7|<span style="color:green"> APROVADO </span>             |
| 184390| 4,85| 2,00|2,50 | 3,44|-     | 1,7|     28|<span style="color:maroon"> REPROVADO FALTA/NOTA </span>  |
| 185760| 9,50| 4,00|-    | 6,20|-     | 6,2|      6|<span style="color:green"> APROVADO </span>             |
| 194182| 3,35| 0,25|3,25 | 3,29|-     | 1,7|      9|<span style="color:maroon"> REPROVADO FALTA/NOTA </span>  |
| 201385| 5,30| 0,25|3,00 | 3,92|4,00  | 4,0|      6|<span style="color:red"> REPROVADO </span>          |
| 202722| 7,75| 1,25|6,50 | 7,00|-     | 7,0|      7|<span style="color:green"> APROVADO </span>             |
| 203263| 9,25| 5,25|-    | 6,85|-     | 6,9|      1|<span style="color:green"> APROVADO </span>             |
| 203845| 5,80| 4,00|5,25 | 5,47|8,50  | 7,0|      1|<span style="color:green"> APROVADO </span>             |
| 203932| 5,60| 0,75|4,00 | 4,64|3,50  | 4,1|      8|<span style="color:red"> REPROVADO </span>          |
| 204163| 5,35| 2,25|3,75 | 4,39|3,75  | 4,1|      6|<span style="color:red"> REPROVADO </span>          |
| 204402| 5,05| 4,00|4,25 | 4,57|5,50  | 5,0|      8|<span style="color:green"> APROVADO </span>             |
| 204523| 7,85| 3,25|5,00 | 6,14|-     | 6,1|      8|<span style="color:green"> APROVADO </span>             |
| 204644| 4,30| 0,00|-    | 1,72|-     | 0,9|     25|<span style="color:maroon"> REPROVADO FALTA/NOTA </span>  |
| 205497| 5,55| 5,75|6,25 | 5,97|-     | 6,0|      4|<span style="color:green"> APROVADO </span>             |
| 205885| 7,75| 4,50|4,75 | 5,95|-     | 6,0|      7|<span style="color:green"> APROVADO </span>             |
| 206917| 5,75| 3,75|2,25 | 4,55|5,50  | 5,0|      4|<span style="color:green"> APROVADO </span>             |
| 207354| 1,90| 0,00|-    | 0,76|-     | 0,4|     12|<span style="color:maroon"> REPROVADO FALTA/NOTA </span>  |
| 214613| 6,80| 1,50|5,75 | 6,17|-     | 6,2|      8|<span style="color:green"> APROVADO </span>             |
| 221444| 6,80| 0,50|0,75 | 3,17|3,75  | 3,5|      6|<span style="color:red"> REPROVADO </span>          |
| 223188| 7,50| 3,00|4,50 | 5,70|9,00  | 7,4|      7|<span style="color:green"> APROVADO </span>             |
| 223638| 4,85| 5,00|4,75 | 4,94|6,00  | 5,5|      6|<span style="color:green"> APROVADO </span>             |
| 228476| 1,90| 0,75|0,50 | 1,21|-     | 0,6|     10|<span style="color:maroon"> REPROVADO FALTA/NOTA </span>  |
  
   

----

### Resumo das Notas 

\    | Min.| 1st Qu.| Median| Mean| 3rd Qu.| Max.|
:----:|:----:|:-------:|:------:|:----:|:-------:|:----:|
**P1** | 1,90|    4,71|   5,78| 6,13|    7,85| 9,50|
**P2** | 0,25|    1,50|   3,75| 3,56|    4,88| 9,75|
**MF** | 0,00|    3,20|   4,96| 4,75|    6,24| 9,61|
**NF** | 0,00|    1,82|   5,25| 4,56|    6,56| 9,61|

\ | APROVADOS | REPROVADOS | REPROVADO FALTA/NOTA |
:-:|:---------:|:------:|:------:|
Frequência | 26 | 8 | 12 |

```{r, echo=FALSE, include=FALSE, warning=FALSE}
library("gdata")
notas = read.xls("/Users/Larissa/Desktop/2S2018/ME414/G_ME414A_2018S2 Notas.xls",sheet=2,header = TRUE)
# notas$S[notas$MF>=6]<-"APROVADO"
# notas$S[notas$MF<6 & notas$Faltas<=8]<-"EXAME"
# notas$S[notas$MF<6 & notas$Faltas>8]<-"REPROVADO"
notas$S[notas$NF>=5]<-"APROVADO"
notas$S[notas$NF<5 & notas$Faltas<=8]<-"REPROVADO"
notas$S[notas$Faltas>8]<-"REPROVADO FALTA/NOTA"
require(xtable)
kable(notas)
notasp1<-notas$P1
notasp1[notasp1==0]<-NA
notasp2<-notas$P2
notasp2[notasp2==0]<-NA
notasmf<-notas$MF
notasf<-notas$NF
faltas<-notas$Faltas

#boxplot(notasp1, horizontal=TRUE,  outline=TRUE,col="lightblue", type=3, ylim=c(0,10))
#abline(v=6,lty=2)
#boxplot(notasp2, horizontal=TRUE,  outline=TRUE,col="lightblue", type=3, ylim=c(0,10))
#abline(v=6,lty=2)
#boxplot(notasf, horizontal=TRUE,  outline=TRUE,col="lightblue", type=3, ylim=c(0,10))
#abline(v=6,lty=2)
a<-summary(notasp1)
b<-rbind(summary(notasp1),summary(notasp2),c(summary(notasmf),0),c(summary(notasf),0))
kable(round(b[,1:6],2))
kable(notas[,c(1:4,6)])
```

```{r, echo=FALSE, include=FALSE}
kable(table(notas$S))
```

```{r, echo=FALSE, fig.width=10, fig.height=5, warning=FALSE}
par(mfrow=c(1,4))
boxplot(notasp1,col="lightblue", type=3, ylim=c(0,10),main="P1")
points(mean(notasp1,na.rm=TRUE))
abline(h=6,lty=2)
boxplot(notasp2,col="lightblue", type=3, ylim=c(0,10),main="P2")
points(mean(notasp2,na.rm=TRUE))
abline(h=6,lty=2)
boxplot(notasmf,col="lightblue", type=3, ylim=c(0,10), main="MF")
points(mean(notasmf))
abline(h=6,lty=2)
boxplot(notasf,col="lightblue", type=3, ylim=c(0,10), main="NF")
points(mean(notasf))
abline(h=5,lty=2)
```


<!-- ```{r, echo=FALSE} -->
<!-- dd <- data.frame(v0=notas$RA, v1=notas$P1, v2=notas$P2, v3=notas$SUB, v4=notas$MF, v5=notas$EXAME, v6=notas$NF,  v7=notas$Faltas, v8=notas$S) -->
<!-- colnames(dd)=c("RA", "P1", "P2", "SUB", "MF", "EXAME", "NF", "Faltas", "S") -->

<!-- datatable(dd, rownames=FALSE) -->
<!-- ``` -->

</div>

